main/routes/coordinatorRoute.py
from flask import Blueprint, url_for, redirect, session, flash, render_template, jsonify, make_response, g
from main.models.dbModel import User, Community,Upload



coordinator_route = Blueprint('coordinator', __name__)


# COORDINATOR SESSION
@coordinator_route.route("/co-dashboard")
def def_coordinator():
     # Check if the user is logged in
    if 'user_id' not in session:
        flash('Please log in first.', 'error')
        return redirect(url_for('dbModel.login'))
    return render_template("coordinator_dashboard.html")


# COMMUNITY PROJECTS
@coordinator_route.route("/co_projects")
def def_co_project():
    if 'user_id' not in session:
        flash('Please log in first.', 'error')
        return redirect(url_for('dbModel.login'))
    return render_template("coordinator_project.html")


def get_current_user():
    if 'user_id' in session:
        # Assuming you have a User model or some way to fetch the user by ID
        user = User.query.get(session['user_id'])
        if user:
            return user.firstname, user.role
    return None, None


@coordinator_route.before_request
def before_request():
    g.current_user, g.current_role = get_current_user()

@coordinator_route.context_processor
def inject_current_user():
    return dict(current_user=g.current_user, current_role=g.current_role)


##################  COMMUNITY  #######################
@coordinator_route.route("/get_community_data")
def get_community_data():
    try:
        community_data = [
        {
            'community': record.community,
            'program': record.program,
            'subprogram': record.subprogram,
            'week': record.week,
            'totalWeek': record.totalWeek,
            'user': record.user
            # Add other fields here
        }
        for record in Community.query.all()
    ]
        return jsonify(community_data)
    except Exception as e:
        # Log the error for debugging
        print(str(e))
        return make_response("Internal Server Error", 500)

@coordinator_route.route("/clear_session")
def clear_session():
    # Clear the user's session
    session.clear()
    
    # Redirect the user to the login page
    return redirect(url_for('dbModel.login'))



# -------------------------   DL FILES-----------------
@coordinator_route.route('/co-files')
def co_files():
    if 'user_id' not in session:
        flash('Please log in first.', 'error')
        return redirect(url_for('dbModel.login'))
    upload_data = Upload.query.all()
    return render_template("coordinatorfiles.html", upload_data=upload_data)

#--------------------CHANGE PASSWORD ---------------
@coordinator_route.route('/co-changepassword')
def def_changepass():
    if 'user_id' not in session:
        flash('Please log in first.', 'error')
        return redirect(url_for('dbModel.login'))
    return render_template('co-changepassword.html')

main/routes/dbModelRoute.py
from flask import Blueprint, url_for, redirect, request, session, flash, render_template, jsonify, make_response, g
from main.models.dbModel import User, Community, Program, Subprogram, Role, Upload
from main import db
from main import Form
from flask import Response


dbModel_route = Blueprint('dbModel', __name__)


@dbModel_route.route("/login", methods=["GET", "POST"])
def login():
    if request.method == "POST":
        username = request.form.get("username")
        password = request.form.get("password")

        # Check the username and password against the database (replace with actual database query)
        user = User.query.filter_by(username=username, password=password).first()

        if user:
            # Store the user's ID in the session to keep them logged in
            session['user_id'] = user.id
            flash('Login successful!', 'success')
            # -if role == 1 go to ADMIN page. if == 0 go coordinator page else error------------------
            if user.role == 'Admin': #Admin
                return redirect(url_for('dbModel.dashboard'))
            else:      #------------------------- COORDINATOR PAGE ---------------------
                return redirect(url_for('coordinator.def_coordinator'))
        else:
            flash('Invalid username or password. Please try again.', 'error')
    return render_template("login.html")


# ADMIN SESSION
@dbModel_route.route("/admin_dashboard")
def dashboard():
     # Check if the user is logged in
    if 'user_id' not in session:
        flash('Please log in first.', 'error')
        return redirect(url_for('dbModel.login'))
    return render_template("dashboard.html")


def get_current_user():
    if 'user_id' in session:
        # Assuming you have a User model or some way to fetch the user by ID
        user = User.query.get(session['user_id'])
        if user:
            return user.firstname, user.role
    return None, None
@dbModel_route.before_request
def before_request():
    g.current_user, g.current_role = get_current_user()

@dbModel_route.context_processor
def inject_current_user():
    return dict(current_user=g.current_user, current_role=g.current_role)

@dbModel_route.route("/clear_session")
def clear_session():
    # Clear the user's session
    session.clear()
    
    # Redirect the user to the login page
    return redirect(url_for('dbModel.login'))

@dbModel_route.route("/result")
def programCSVresult():
    if 'user_id' not in session:
        flash('Please log in first.', 'error')
        return redirect(url_for('dbModel.login'))
    return redirect(url_for('randomForest.programOneRow'))


#FOR USER CRUD

@dbModel_route.route("/manage_account")
def manage_account():
    if 'user_id' not in session:
        flash('Please log in first.', 'error')
        return redirect(url_for('dbModel.login'))
     # Fetch all user records from the database
    all_data = User.query.all()
    role = Role.query.all()
    program8 = Program.query.all()
    return render_template("manage_account.html", users = all_data, role = role, program8=program8)

@dbModel_route.route("/add_account", methods=["POST"])
def add_account():
    if 'user_id' not in session:
        flash('Please log in first.', 'error')
        return redirect(url_for('dbModel.login'))
    
    if request.method == "POST":
        username = request.form.get("username")
        firstname = request.form.get("firstname")
        lastname = request.form.get("lastname")
        password = request.form.get("password")
        role = request.form.get("role")
        program = request.form.get("program")
        # Check if the username already exists in the database
        existing_user = User.query.filter_by(username=username).first()
        if existing_user:
            flash('Username already exists. Please choose a different username.', 'error')
        else:
            # Create a new user without hashing the password
            new_user = User(username=username, firstname=firstname, lastname=lastname, password=password, role = role, program = program)

            try: 
                db.session.add(new_user)
                db.session.commit()
                flash('Account created successfully!', 'success')
            except Exception as e:
                db.session.rollback()
                flash('An error occurred while creating the account. Please try again.', 'error')
                # You may also want to log the exception for debugging purposes
    return redirect(url_for('dbModel.manage_account'))

@dbModel_route.route('/edit_account', methods=['POST'])
def edit_account():
    if 'user_id' not in session:
        flash('Please log in first.', 'error')
        return redirect(url_for('dbModel.login'))
    
    if request.method == 'POST':
        user_id = request.form.get('id')  # Get the user ID from the form
        new_username = request.form['new_username']
        new_firstname = request.form['new_firstname']
        new_lastname = request.form['new_lastname']
        new_password = request.form['new_password']
        new_role = request.form['new_role']
        new_program = request.form['new_program']
        
        
        # Query the user by ID
        user = User.query.get(user_id)
        
        if user:
            # Update the user's information
            user.username = new_username
            user.firstname = new_firstname
            user.lastname = new_lastname
            user.password = new_password
            user.role = new_role
            user.program = new_program

            # Commit the changes to the database
            db.session.commit()
            flash('Account updated successfully!', 'success')
        else:
            flash('User not found. Please try again.', 'error')

        return redirect(url_for('dbModel.manage_account'))

@dbModel_route.route('/delete_account/<int:id>', methods=['GET'])
def delete_account(id):
    if 'user_id' not in session:
        flash('Please log in first.', 'error')
        return redirect(url_for('dbModel.login'))
    
    user = User.query.get(id)

    if user:
        try:
            # Delete the user from the database
            db.session.delete(user)
            db.session.commit()
            flash('Account deleted successfully!', 'success')
        except Exception as e:
            db.session.rollback()
            flash('An error occurred while deleting the account. Please try again.', 'error')
            # You may want to log the exception for debugging purposes
    else:
        flash('User not found. Please try again.', 'error')

    return redirect(url_for('dbModel.manage_account'))



##################  FOR COMMUNITY PROJECT  #######################
@dbModel_route.route("/coordinator")
def coordinator():
    if 'user_id' not in session:
        flash('Please log in first.', 'error')
        return redirect(url_for('dbModel.login'))
    return render_template("coordinator.html")



##################  FOR COMMUNITY CRUD  #######################
@dbModel_route.route("/get_community_data")
def get_community_data():
    try:
        community_data = [
        {
            'community': record.community,
            'program': record.program,
            'subprogram': record.subprogram,
            'week': record.week,
            'totalWeek': record.totalWeek,
            'user': record.user
            # Add other fields here
        }
        for record in Community.query.all()
    ]
        return jsonify(community_data)
    except Exception as e:
        # Log the error for debugging
        print(str(e))
        return make_response("Internal Server Error", 500)

@dbModel_route.route("/manage_community")
def manage_community():
    form = Form()
    placeholder_choice = ("", "-- Select Program --")
    form.program.choices = [placeholder_choice[1]] + [program.program for program in Program.query.all()]
    form.program.default = ""
    form.process()
    if 'user_id' not in session:
        flash('Please log in first.', 'error')
        return redirect(url_for('dbModel.login'))
     # Fetch all user records from the database
    all_data = Community.query.all()
    program8 = Program.query.all()
    user1 = User.query.all()
    return render_template("community.html", community = all_data, form=form, program8=program8, user1 = user1)

@dbModel_route.route("/subprogram/<get_subprogram>")
def subprogram(get_subprogram):
    sub = Subprogram.query.filter_by(program=get_subprogram).all()
    subArray = [program.subprogram for program in sub]  # Extract the subprograms from the query result
    return jsonify({'subprogram': subArray})

#fetch for user
@dbModel_route.route("/subprogram1/<get_program>")
def get_program(get_program):
    sub = User.query.filter_by(program=get_program).all()
    subArray = [user.username for user in sub]  
    return jsonify({'user': subArray})


@dbModel_route.route("/add_community", methods=["POST"])
def add_community():
    if 'user_id' not in session:
        flash('Please log in first.', 'error')
        return redirect(url_for('dbModel.login'))
    
    if request.method == "POST":
        community = request.form.get("community")
        program = request.form.get("program")
        subprogram = request.form.get("subprogram")
        week = request.form.get("week")
        totalWeek = request.form.get("totalWeek")
        user = request.form.get("user")

        # Check if a community with the same values for 'community' and 'subprogram' already exists
        existing_community = Community.query.filter_by(community=community, subprogram=subprogram).first()

        if existing_community:
            flash('This combination of community and subprogram already exists. Please choose a different combination.', 'error')
        else:
            new_community = Community(community=community, program=program, subprogram=subprogram, week=week, totalWeek=totalWeek, user=user)

            try:

main/templates/admin_dashboard.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CESU WEB APPLICATION</title>

    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Sharp:opsz,wght,FILL,GRAD@24,400,0,0" />
    <link rel="stylesheet" href="/static/css/dashboard.css">
    <link rel="stylesheet" href="/static/css/admin_dashboard.css">
    <link rel="stylesheet" href="/static/css/programCSVresult.css">
    <link rel="stylesheet" href="/static/css/community.css">
    <link rel="stylesheet" href="/static/css/manage_account.css">
    <link rel="stylesheet" href="/static/css/coordinator.css">
    <link rel="stylesheet" href="/static/css/program.css">
    <link rel="stylesheet" href="/static/css/dlfiles.css">
    <link rel="stylesheet" href="/static/css/changepassword.css">
    <link rel="stylesheet" href="static/css/coordinator_dashboard.css">

    
    
</head>
<body>
    <div class="container1 ">
        <aside class="sticky-top">
            <div class="top">
                <div class="logo">
                    <img src="/static/images/CESO.png" alt="">
                    <span class="cesu" id="dashboardLink">CE
                        <span class="su">SU</span>
                    </span>
                </div>
                <div class="close" id="close-btn">
                    <span class="material-symbols-sharp">close</span>
                </div>
            </div>
            <div class="sidebar">
                <a href="{{ url_for('dbModel.dashboard') }}" class="sidebar-link">
                    <span class="material-symbols-sharp">dashboard</span>
                    <h3>Dashboard</h3>
                </a>
                <a href="{{ url_for('dbModel.manage_community') }} " class="sidebar-link">
                    <span class="material-symbols-sharp" >groups</span>
                    <h3>Community</h3>
                </a>
                <a href="{{ url_for('dbModel.coordinator') }} " class="sidebar-link">
                    <span class="material-symbols-sharp">
                        monitoring
                        </span>
                    <h3>Community Projects</h3>
                </a>
                <a href="{{ url_for('dbModel.manage_account') }}"class="sidebar-link">
                    <span class="material-symbols-sharp">manage_accounts</span>
                    <h3>Manage Account</h3>
                </a>
                
                <a href="{{ url_for('randomForest.program') }}"class="sidebar-link">
                    <span class="material-symbols-sharp">neurology</span>
                    <h3>Program Recommendation</h3>
                </a>
                <!---------------------------   NEWLY ADDED    -------------------------------->
                <a href="{{ url_for('dbModel.files') }}"class="sidebar-link">
                    <span class="material-symbols-sharp">
                        folder
                        </span>
                    <h3>Files</h3>
                </a>
                
            </div>
        </aside>
        <main>
            {% block content %}{% endblock %}

            <div class="space" style="margin-top: 5rem;"></div>
        </main>
        <div class="right">
            <div class="top">
                <button id="menu-btn">
                    <span class="material-symbols-sharp">menu</span>
                </button>
                <div class="theme-toggler">
                    <span class="material-symbols-sharp active">light_mode</span>
                    <span class="material-symbols-sharp">dark_mode</span>
                </div>
                <div class="profile">
                    <div class="profile-info">
                        <p>Hi, <b>{{current_user}}</b></p>
                        <small class="text-muted">{{current_role}}</small>
                    </div>
                    <div class="profile-photo" id="profile-photo" onclick="toggleDropdown()">
                        <img src="/static/images/CESO.png" alt="">
                        <div class="dropdown-content" id="dropdown-content">
                            <div class="password-div"><a class="password-button"  href="{{ url_for('dbModel.changepass') }}" id="password-button">Change Password</a></div>
                            <div class="logout-hover"><a class="logout-button" href="{{ url_for('dbModel.clear_session') }}" id="logout-button">Logout</a></div>
                        </div>
                    </div>
                </div>
                
            </div>
            <!--End of top-->
            <div class="recent-updates">
              
                <div class="updates">
                    
                    <div id="date-container">
                        <!-- The current date and day will be displayed here -->
                    </div>
                </div>
            </div>
        </div>
    </div>

   
 <script src="/static/js/admin_dashboard.js"></script>

<script>
  document.addEventListener("DOMContentLoaded", function() {
  const sidebarLinks = document.querySelectorAll(".sidebar-link");

  sidebarLinks.forEach(function(link) {
    link.addEventListener("click", function(event) {
      // Prevent the default behavior of the link temporarily
      event.preventDefault();

      // Add "active" class to the clicked link
      link.classList.add("active");

      // Store the active link information in local storage
      localStorage.setItem("activeLink", link.getAttribute("href"));

      // Wait for a short period (e.g., 500 milliseconds) to let the styles apply
      setTimeout(() => {
        // Remove the "active" class
        link.classList.remove("active");

        // Perform the navigation to the link's href after a delay
        window.location.href = link.getAttribute("href");
      }, 10); // Adjust the delay as needed
    });
  });

  // Check if there is an active link in local storage and apply the "active" class
  const activeLink = localStorage.getItem("activeLink");
  if (activeLink) {
    const activeLinkElement = document.querySelector(`[href="${activeLink}"]`);
    if (activeLinkElement) {
      activeLinkElement.classList.add("active");
    }
  }
});
</script>

<!-- ON CLICK CESU-->
<script>
    document.getElementById("dashboardLink").addEventListener("click", function() {
        window.location.href = "{{ url_for('dbModel.dashboard') }}";
    });
</script>
</body>
</html>

main/templates/co-changepassword.html
{% extends "coordinator_layout.html" %}
{% block coordinator %}
<div class="title">
    <h1>
        <span class="material-symbols-sharp locksharp">
            lock
            </span> <h3 class="changetxt">Change Password</h3>
    </h1>
</div>
<div class="password-container">

        
        <form method="POST" action="{{ url_for('coordinator.def_changepass') }}" id="password-form">
          
            <div class="form-group">
                <label class="change_lbl" for="">Current Password</label>
                <input class="form-control" type="password" name="old_password" required="">
            </div>
            
            <div class="form-group">
                <label class="change_lbl" for="">New Password *</label>
                <input class="form-control" type="password" name="new_password" minlength="8" required="">
                <span class="text-info"><small><i>* minimum of 8 characters</i></small></span>
            </div>

            <div class="form-group">
                <label class="change_lbl" for="">Confirm New Password</label>
                <input class="form-control" type="password" name="confirm_password" required="">
            </div>

                <button class="btn btn-success" type="submit" id="save-btn">
                    <span class="material-symbols-sharp savesharp">
                        save
                    </span> &nbsp;<span class="save">SAVE</span>
                </button>
        </form>  
   
</div>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>



{% endblock %}

main/templates/manage_account.html
{% extends "admin_dashboard.html" %}
{% block content %}

<div class="manageUser">
    <div class="jumbotron">
        <h2 style="margin-bottom: 1rem;">Manage <b>Accounts</b> 
            <button type="button" class="btn-add" data-bs-toggle="modal" data-bs-target="#mymodal" style="float: right;"><span class="material-symbols-sharp" style="float: right;">add</span></button></h2>
            <table class="table">
                <tr>
                    <th>ID</th>
                    <th>Username</th>
                    <th>Firstname</th> 
                    <th>Lastname</th> 
                    <th>Password</th>    
                    <th>Role</th>         
                    <th>Program</th>              
                    <th>Action</th>
                </tr>
                 {% for row in users %}
                 <tr>
                    <td>{{ row.id }}</td>
                    <td>{{ row.username }}</td>
                    <td>{{ row.firstname }}</td>
                    <td>{{ row.lastname }}</td>
                    <td>{{ row.password }}</td>
                    <td>{{ row.role }}</td>
                    <td>{{ row.program }}</td>
                    <td>
                        <a href="{{ url_for('dbModel.edit_account', id=row.id) }}" class="btn-edit" data-bs-toggle="modal" data-bs-target="#modaledit{{row.id}}">Edit</a>
                        <a href="{{ url_for('dbModel.delete_account', id=row.id) }}" class="btn-delete" onclick="return confirm('Are you sure to delete?')">Delete</a>
                    </td>
                </tr>

                <!-- Modal for Edit -->
                <div id="modaledit{{row.id}}" class="modal">
                    <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h4 class="modal-title">Edit Account</h4>
                            </div>

                            <div class="modal-body">
                                <form action="{{ url_for('dbModel.edit_account') }}" method="POST">
                                    <div class="form-group">
                                        <label>Username:</label>
                                        <input type="text" class="form-control" name="new_username" value="{{row.username}}" required>
                                    </div>
                                    <div class="form-group">
                                        <label>Firstname:</label>
                                        <input type="text" class="form-control" name="new_firstname" value="{{row.firstname}}" required>
                                    </div>
                                    <div class="form-group">
                                        <label>Lastname:</label>
                                        <input type="text" class="form-control" name="new_lastname" value="{{row.lastname}}" required>
                                    </div>
                                    <div class="form-group">
                                        <label>Password:</label>
                                        <input type="text" class="form-control" name="new_password" value="{{row.password}}" required>
                                    </div>
                                    <div class="form-group" >
                                    <label for="new_role">Role:</label>
                                    <select class="form-select" name="new_role"required>
                                        <option value="{{row.role}}" selected style="display: none;">{{row.role}}</option>
                                        {% for r in role %}
                                            <option value="{{ r.role }}">{{ r.role }}</option>
                                        {% endfor %}
                                    </select>
                                    </div>
                                    <div class="form-group">
                                    <label for="new_program">Program:</label>
                                    <select class="form-select" name="new_program" required>
                                        <option value="{{row.program}}" selected style="display: none;">{{row.program}}</option>
                                            {% for p in program8 %}
                                            <option value="{{ p.program }}">{{ p.program }}</option>
                                            {% endfor %}
                                    </select>
                                    </div>
                                    <input type="hidden" name="id" id="edit-id" value="{{row.id}}">
                                        <div class="form-group">
                                            <button class="btn-submit" type="submit">Save Changes</button>
                                        </div>
                                </form>
                            </div>

                            <div class="modal-footer">
                                <button type="button" class="btn-close" data-bs-dismiss="modal">Close</button>
                            </div>
                        </div>
                    </div>
                </div><!--end edit modal-->
                {% endfor %}
            </table>

                <!--Modal for adding -->
                <div id="mymodal" class="modal">
                    <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h4 class="modal-title">Add account</h4>
                            </div>
                            <div class="modal-body">
                                <form action="{{ url_for('dbModel.add_account') }}" method="POST">
                                        <div class="form-group">
                                            <label>Username:</label>
                                            <input type="text" class="form-control" name="username" required>
                                        </div>
                                        <div class="form-group">
                                            <label>Firstname:</label>
                                            <input type="text" class="form-control" name="firstname" required>
                                        </div>
                                        <div class="form-group">
                                            <label>Lastname:</label>
                                            <input type="text" class="form-control" name="lastname" required>
                                        </div>
                                        <div class="form-group">
                                            <label>Password:</label>
                                            <input type="password" class="form-control" name="password" required>
                                        </div>

                                        <div class="form-group">
                                            <label for="role">Role:</label>
                                            <select class="form-control" name="role" required>
                                                <option selected disabled>-- s e l e c t --</option>  <!-- Placeholder option -->
                                                {% for r in role %}
                                                    <option value="{{ r.role }}">{{ r.role }}</option>
                                                {% endfor %}
                                            </select>
                                        </div>

                                        <div class="form-group">
                                            <label for="program">Program:</label>
                                            <select class="form-control" name="program" required>
                                                <option selected disabled >-- s e l e c t --</option>  <!-- Placeholder option -->
                                                {% for p in program8 %}
                                                    <option value="{{ p.program }}">{{ p.program }}</option>
                                                {% endfor %}
                                            </select>
                                        </div>

                                        <div class="form-group">
                                            <button class="btn-submit btn-primary" type="submit">Add account</button>
                                        </div>
                                </form>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn-close" data-bs-dismiss="modal">Close</button>
                            </div>
                        </div>
                    </div>
                </div> <!--end add modal-->
    </div><!--end jumbotron-->   
</div>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>

{% endblock %}